<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType><TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF><UseWindowsForms>true</UseWindowsForms><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable>
    <AssemblyName>Razret</AssemblyName><Version>0.7.1</Version><Product>Razret</Product><Title>Razret</Title>
    <ApplicationIcon>Assets/razret.ico</ApplicationIcon>
    <UpdateRepository Condition="'$(UpdateRepository)' == ''">x3sh/razret</UpdateRepository>
  </PropertyGroup>
  <ItemGroup><Using Remove="System.Windows.Forms"/><Using Remove="System.Drawing"/></ItemGroup>
  <ItemGroup><AssemblyMetadata Include="UpdateRepository" Value="$(UpdateRepository)" /></ItemGroup>
  <ItemGroup><Resource Include="Assets/razret-icon.png"/><Content Include="Assets/razret.ico" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" ExcludeFromSingleFile="true"/></ItemGroup>
</Project>
